### ISSUE TITLE
Double Websites

### ISSUE THREAD

**Issue by PCTipsGR** [NeotiDev/mardatonne-doc#1]
Websites exist at both https://mardatonne.tk and https://mardatonne.js.org. 

I think that at least one of them has to be redirecting to another (probably the .tk version if you want to keep this).

**Comment by yagizhan49** [comment]
They both use the same source. They deploy at the same time from the same source, so there is no need to disable one of them.

**Comment by PCTipsGR** [comment]
Wouldn't it be bad for SEO though?
